spring.application.name=ProductionGradeRAGApp


server.port=${SERVER_PORT:8080}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver



# ===============================
# JPA / Hibernate
# ===============================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


####################################################
# JWT
####################################################


jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

####################################################
# EMAIL
####################################################


spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}

spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


####################################################
# FILE UPLOADS
####################################################

spring.servlet.multipart.max-file-size=${MAX_FILE_SIZE:20MB}
spring.servlet.multipart.max-request-size=${MAX_REQUEST_SIZE:20MB}



####################################################
# DOCUMENT LIMITS
####################################################

app.max-documents-per-user=${MAX_DOCUMENTS_PER_USER:100}



####################################################
# VECTOR STORE
####################################################

spring.ai.vectorstore.pgvector.initialize-schema=true
spring.ai.openai.chat.options.model=${CHAT_MODEL}

spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.embedding.options.model=${EMBEDDING_MODEL}



###########
# LOGGING
####################################################

logging.level.root=INFO
logging.level.org.springframework.security=WARN
logging.level.org.hibernate.SQL=WARN


####################################################
# CORS
####################################################


app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS}
#app.cors.allowed-origins=http://localhost:5173


####################################################
# OTP
####################################################

app.otp.expiry-minutes=${OTP_EXPIRY_MINUTES:10}



####################################################
# HEALTH / ACTUATOR
####################################################

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always



# GRANTING ACCESS TO THE USERS

rag.access.request.mail=${EMAIL_TO_ACCES_GRANTING}





server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true