spring.application.name=ProductionGradeRAGApp


server.port=3214

spring.datasource.url=jdbc:postgresql://localhost:5433/student_db
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#spring.autoconfigure.exclude=org.springframework.ai.vectorstore.pgvector.autoconfigure.PgVectorStoreAutoConfiguration

# ===============================
# JPA / Hibernate
# ===============================

spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect



spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

#gemini.api-key=AQ.Ab8RN6JhxiHraV5MzG5WZitFJY7qY7gM50sJVLGkT77VLVZQrg

jwt.secret=mySuperSecureJwtSecretKeyThatIsAtLeast32CharactersLong123!
jwt.expiration=1800000

# GCP Project
#vertex.ai.project-id=rag-builder-java
#vertex.ai.location=us-central1
#spring.ai.vertex.ai.gemini.model=gemini-2.5-flash

# Optional (if you are not using default credentials)
#GOOGLE_APPLICATION_CREDENTIALS=c:/keys/service-account




spring.ai.openai.embedding.options.model=text-embedding-3-small
spring.ai.openai.api-key=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


spring.ai.openai.chat.options.model=gpt-4o-mini
spring.ai.vectorstore.pgvector.initialize-schema=true


spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.username=krishna.kishore86@gmail.com
spring.mail.password=whaantykqzbmfnke

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


